name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Google Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Debug info
        run: |
          node -v
          npm -v
          ls -la

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm ci
        working-directory: ./tia_vicenta

      - name: Run unit tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
        working-directory: ./tia_vicenta

      - name: Run e2e tests
        run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --configuration=production
        working-directory: ./tia_vicenta

      - name: Build for production
        run: npm run build --prod
        working-directory: ./tia_vicenta

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIA_VICENTA }}'
          channelId: live
          projectId: tia-vicenta
